PracticaWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from forkilla import views


# API
router = routers.DefaultRouter()
router.register(r'restaurants', views.RestaurantViewSet, base_name='Restaurants')

urlpatterns = [
    url(r'^forkilla/', include('forkilla.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$',  login,  name='login'),
    url(r'^accounts/logout/$',  logout,  {'next_page': '/forkilla'}, name='logout'),
    url(r'^', include('forkilla.urls')),
    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    ]

#handler404 = 'forkilla.views.handler404'
#handler500 = 'forkilla.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forkilla/urls.py
from django.conf.urls import url

from . import views

listOfAddresses = ["localhost:8000"] # Rellenar con direcciones ip

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^restaurant/(?P<restaurant_number>.*)/review$', views.add_comment, name='review'),
    url(r'^register/$', views.register, name='register'),
    url(r'^restaurants/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/(?P<category>.*)$', views.restaurants, name='restaurants'),
    url(r'^restaurant/(?P<restaurant_number>.*)/', views.details, name='details'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^reservation_list/$', views.reservation_list, name='reservation_list'),
    url(r'^delete_reservation/$', views.delete_reservation, name='delete_reservation'),
    url(r'^comparator$', views.comparator, {'ips' : listOfAddresses}, name='comparator',),
]

forkilla/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.core.validators import MinValueValidator


class Restaurant(models.Model):
    CATEGORIES = (
        ("Rice", "Rice"),
        ("Fusi", "Fusion"),
        ("BBQ", "Barbecue"),
        ("Chin", "Chinese"),
        ("Medi", "Mediterranean"),
        ("Crep", "Creperie"),
        ("Hind", "Hindu"),
        ("Japa", "Japanese"),
        ("Ital", "Italian"),
        ("Mexi", "Mexican"),
        ("Peru", "Peruvian"),
        ("Russ", "Russian"),
        ("Turk", "Turkish"),
        ("Basq", "Basque"),
        ("Vegy", "Vegetarian"),
        ("Afri", "African"),
        ("Egyp", "Egyptian"),
        ("Grek", "Greek")
    )
    _d_categories = dict(CATEGORIES)

    restaurant_number = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=50)
    menu_description = models.TextField()
    price_average = models.DecimalField(max_digits=5, decimal_places=2)
    is_promot = models.BooleanField()
    rate = models.DecimalField(max_digits=3, decimal_places=1)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    featured_photo = models.CharField(max_length=300)
    category = models.CharField(max_length=5, choices=CATEGORIES)
    capacity = models.PositiveIntegerField(max_length=3)

    def get_human_category(self):
        return self._d_categories[self.category]

    def __str__(self):
        return ('[**Promoted**]' if self.is_promot else '') + "[" + self.category + "] " \
                                                                                    "[" + self.restaurant_number + "] " + self.name + " - " + self.menu_description + " (" + str(
            self.rate) + ")" \
                         ": " + str(self.price_average) + u" €"


class Reservation(models.Model):
    SLOTS = (
        ("morning_first", "12h00"),
        ("morning_second", "13h00"),
        ("morning_third", "14h00"),
        ("morning_fourth", "15h00"),
        ("evening_first", "20h00"),
        ("evening_second", "21h00"),
        ("evening_third", "22h00"),
    )
    _d_slots = dict(SLOTS)
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    day = models.DateField(default=datetime.now)
    time_slot = models.CharField(max_length=15, choices=SLOTS)
    num_people = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def get_human_slot(self):
        return self._d_slots[self.time_slot]


class ViewedRestaurants(models.Model):
    id_vr = models.AutoField(primary_key=True)
    restaurant = models.ManyToManyField(Restaurant, through='RestaurantInsertDate')


class RestaurantInsertDate(models.Model):
    viewedrestaurants = models.ForeignKey(ViewedRestaurants, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']


class Review(models.Model):
    RATES = (
        ("0", "0"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
    )

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    ratio = models.CharField(max_length=1,choices=RATES, default='-')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

forkilla/forms.py
from django import forms

from .models import Reservation, Review


class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ["day", "time_slot", "num_people"]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["comment","ratio" ]

forkilla/views.py
from django.db.models import Q
from django.shortcuts import render, reverse

from django.http import HttpResponseRedirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from .models import Restaurant, ViewedRestaurants, RestaurantInsertDate, Reservation, Review
from .forms import ReservationForm
from datetime import datetime

# Restful
from rest_framework import viewsets, permissions
from .serializers import RestaurantSerializer


@login_required
def add_comment(request, restaurant_number=""):
    restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
    if request.method == "POST":

        comment = request.POST['comment']
        ratio = request.POST['ratio']
        user = request.user

        review = Review()
        review.restaurant = restaurant
        review.user = user
        review.comment = comment
        review.ratio = ratio

        review.save()

    return details(request, restaurant_number)


def index(request):
    viewedrestaurants = _check_session(request)
    restaurants_by_city = Restaurant.objects.filter(is_promot="True")
    context = {
        'restaurants': restaurants_by_city,
        'viewedrestaurants': viewedrestaurants
    }

    return render(request, 'forkilla/home.html', context)


def restaurants(request, city="", category=""):
    viewedrestaurants = _check_session(request)
    promoted = False
    if city:
        if category:
            restaurants_by_city = Restaurant.objects.filter(city__iexact=city, category__iexact=category)
        else:
            restaurants_by_city = Restaurant.objects.filter(city__iexact=city).order_by('category')
    else:
        restaurants_by_city = Restaurant.objects.filter(is_promot="True")
        promoted = True

    context = {
        'city': city,
        'category': category,
        'restaurants': restaurants_by_city,
        'promoted': promoted,
        'viewedrestaurants': viewedrestaurants
    }

    return render(request, 'forkilla/restaurants.html', context)


def details(request, restaurant_number):
    try:
        viewedrestaurants = _check_session(request)
        restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
        lastviewed = RestaurantInsertDate(viewedrestaurants=viewedrestaurants, restaurant=restaurant)
        lastviewed.save()

        reviews = Review.objects.filter(restaurant=restaurant)
        if reviews:
            print("there's a review")
            context = {
                'restaurant': restaurant,
                'viewedrestaurants': viewedrestaurants,
                'reviews': reviews,
            }
        else:
            print("No review")
            context = {
                'restaurant': restaurant,
                'viewedrestaurants': viewedrestaurants,
            }

    except Restaurant.DoesNotExist:
        return handler404(request)

    return render(request, 'forkilla/details.html', context)


@login_required
def reservation(request):
    try:
        if request.method == "POST":
            form = ReservationForm(request.POST)
            if form.is_valid():

                restaurant_number = request.session["reserved_restaurant"]
                restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
                user = request.user
                current_reservations = Reservation.objects.filter(restaurant=restaurant,
                                                                  time_slot=request.POST["time_slot"],
                                                                  day=request.POST["day"])

                reservations = sum([i.num_people for i in current_reservations])
                reservations += int(request.POST["num_people"]) # si falla el cast habria que mandar un 500

                if current_reservations:
                    if reservations > restaurant.capacity:
                        request.session["result"] = "Error"

                    else:
                        resv = form.save(commit=False)
                        resv.restaurant = restaurant
                        resv.user = user
                        resv.save()
                        request.session["reservation"] = resv.id
                        request.session["result"] = "OK"

                else:
                    resv = form.save(commit=False)
                    resv.restaurant = restaurant
                    resv.user = user
                    resv.save()
                    request.session["reservation"] = resv.id
                    request.session["result"] = "OK"

            else:
                request.session["result"] = form.errors

            return HttpResponseRedirect(reverse('checkout'))

        elif request.method == "GET":
            restaurant_number = request.GET["reservation"]
            restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
            request.session["reserved_restaurant"] = restaurant_number

            form = ReservationForm()

            viewedrestaurants = _check_session(request)
            context = {
                'restaurant': restaurant,
                'viewedrestaurants': viewedrestaurants,
                'form': form,
            }

    except Restaurant.DoesNotExist:
        return handler404(request)

    return render(request, 'forkilla/reservation.html', context)


def _check_session(request):
    if "viewedrestaurants" not in request.session:
        viewedrestaurants = ViewedRestaurants()
        viewedrestaurants.save()
        request.session["viewedrestaurants"] = viewedrestaurants.id_vr
    else:
        viewedrestaurants = ViewedRestaurants.objects.get(id_vr=request.session["viewedrestaurants"])
    return viewedrestaurants


def checkout(request):
    result = request.session["result"]

    restaurant_number = request.session["reserved_restaurant"]
    restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)

    if result == "OK":
        current_reservation = Reservation.objects.get(id=request.session["reservation"])

        del request.session["reserved_restaurant"]
        del request.session["reservation"]
        del request.session["result"]

    else:
        current_reservation = None

    context = {
        'restaurant': restaurant,
        'reservation': current_reservation,
        'result': result,
        'viewedrestaurants': _check_session(request)
    }

    return render(request, 'forkilla/checkout.html', context)


@login_required
def reservation_list(request):
    user = request.user

    date = datetime.today()
    past_reservations = Reservation.objects.filter(user=user, day__lt=date).order_by("day", "time_slot")
    future_reservations = Reservation.objects.filter(user=user, day__gte=date).order_by("day", "time_slot")

    context = {
        'past_reservations': past_reservations,
        'future_reservations': future_reservations,
        'viewedrestaurants': _check_session(request)
    }

    return render(request, 'forkilla/my_reservations.html', context)


@login_required
def delete_reservation(request):
    reservation_id = request.GET['reservation_id']

    Reservation.objects.filter(id=reservation_id).delete()

    return HttpResponseRedirect(reverse('reservation_list'))


def search(request):

    query = request.GET.get('q', '')
    if query:
        found_restaurants = Restaurant.objects.filter(
            Q(name__icontains=query) | Q(city__icontains=query) |
            Q(category__icontains=query)
        ).distinct()

    else:
        found_restaurants = None
    context = {
        'restaurants': found_restaurants,
        'name': query,
        'viewedrestaurants': _check_session(request)
    }

    return render(request, 'forkilla/restaurants.html', context)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {'form': form})


class RestaurantViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Restaurants to be viewed or edited.
    """
    serializer_class = RestaurantSerializer
    permission_classes = (permissions.DjangoModelPermissionsOrAnonReadOnly,)

    def get_queryset(self):
        category = self.request.query_params.get('category', None)
        city = self.request.query_params.get('city', None)
        price_average = self.request.query_params.get('price_average', None)

        your_values = {'category': category, 'city': city}
        arguments = {}
        for k, v in your_values.items():
            if v:
                arguments[k] = v

        queryset = Restaurant.objects.filter(**arguments)

        if price_average:
            queryset = queryset.exclude(price_average__gt=price_average)

        return queryset.order_by("price_average")


def handler404(request):
    response = render(request, 'forkilla/404.html', {})
    response.status_code = 404
    return response


def handler500(request):
    response = render(request,'forkilla/500.html', {})
    response.status_code = 500
    return response



def comparator(request, ips):
    context = {
        'viewedrestaurants': _check_session(request),
        'ips' : ips,
    }
    return render(request, "forkilla/comparator.html", context)

templates/forkilla/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles  %}
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <title>Forkilla - {% block title %}{% endblock %}</title>

    <style>

        .featured-image {
            width: 100%;
            height: 18rem;
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
        }

        .card{
            width: 100%;
            margin-top: 1rem;
            margin-bottom: 1em;
        }

        .navbar-brand {
            display: inline-block;
            padding-top: .3125rem;
            padding-bottom: .3125rem;
            margin-right: 1rem;
            font-size: 1.7rem;
            line-height: inherit;
            white-space: nowrap;
            font-weight: bold;
        }

        #card-home{
            height: 90%;
        }

    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-dark fixed-top" style="background-color: rgba(0,0,0,1)!important;">
            <!-- Navbar content -->
            <a class="navbar-brand" id="brand" href="{% url 'index' %}" style="font-family: 'Arima Madurai', cursive;">Forkilla</a>
            <form type="get" action="{% url 'search'%}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" id="search_box" type="text" name="q" value="{{query|escape}}" placeholder="Search...">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'comparator'%}">Comparator</a>
                <div class="dropdown">
                    <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{user.username}}
                    </button>
                    <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'reservation_list' %}">My reservations</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
            {% else %}
                <div class="btn-group" role="group">
                    <a class="btn btn-primary btn-md" href="{% url 'login' %}">Log In</a>
                    <a class="btn btn-outline-light btn-md" href="{% url 'register' %}">Register</a>
                </div>
            {% endif %}
        </nav>
    </header>

    <div class="container-fluid" style="font-family: 'Arima Madurai', cursive; margin-top: 80px; ">

        {% block content%}
        {% endblock %}

        <br>
        <div class="jumbotron" style="width: 100%;">
            <div class="list-group list-group-flush">
                <h4 class="list-group-item list-group-item-action active" style="text-align: center; border-radius: 0.5rem;">Your last viewed Restaurants:</h4>
                <div class="d-flex w-100 justify-content-between">
                    <form action="{% url 'reservation'%}" method="GET" style="width: 100%; text-align: center; align-items: center;">
                        {% for restaurant in viewedrestaurants.restaurantinsertdate_set.all|slice:"5"%}
                            <div class="list-group-item" style="background: transparent;">
                                <a href="{% url 'details' restaurant.restaurant.restaurant_number%}">{{restaurant.restaurant.name}} </a> ({{restaurant.restaurant.rate}}) : 	{{restaurant.restaurant.menu_description}}
                                <button class="btn btn-primary" type="submit" name="reservation" value={{restaurant.restaurant.restaurant_number}}>    Book</button>
                                <br>
                            </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/forkilla/checkout.html
{% extends 'forkilla/base.html' %}
{% block title %}{{restaurant.name}} Reservation{% endblock %}
{% block content %}

<div style="margin-top: 1rem; ">
    {%  if result == "OK" %}
    <div class="card text-white bg-success mb-3" style="width: 100%;">
        <div class="card-header" style="text-align: center;">SUCCESS!</div>
        <div class="card-body">
          <h3 class="card-title"  style="text-align: center">Reservation made succesfully</h3>
          <div class="card-text"  style="text-align: center">
            <ul>
                <li> Restaurant: {{ restaurant.name }} </li>
                <li> Reservation ID: {{ reservation.id }} </li>
                <li> Date: {{ reservation.day }}, {{ reservation.get_human_slot }} </li>
                <li> Number of people: {{ reservation.num_people }}</li>
            </ul>
          </div>
        </div>
      </div>
    {% else %}

      <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
        <div class="card-header">ERROR</div>
        <div class="card-body">
          <h5 class="card-title">Reservation could not be done</h5>
          <p class="card-text">Reservation could not be done for the restaurant {{restaurant.name}}</p>
        </div>
      </div>

    {% endif %}
    <div>
        <a class="btn btn-primary btn-block" href="{% url 'index'%}">Home</a>
    </div>
</div>
{% endblock %}

templates/forkilla/details.html
{% extends 'forkilla/base.html' %}
{% block title %}{{restaurant.name}}{% endblock %}
{% block content %}

<nav aria-label="breadcrumb"  style="margin-top: 1rem;">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'restaurants' restaurant.city %}">{{restaurant.city|title}}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'restaurants' restaurant.city restaurant.category %}">{{restaurant.category|title}}</a></li>
    <li class="breadcrumb-item"> {{restaurant.name}} </li>
  </ol>
</nav>

<div class="card mb-3" style="width: 100%;">
    <div class="row no-gutters">
        <div class="col-md-4" >
            <img src="{{restaurant.featured_photo}}" class="card-img" style="height: 100%;" alt="{{restaurant.name}}">
        </div>
        <div class="col-md-8">
            <div class="card-body">
               <h3 class="card-title" style="text-align: center;"><strong>{{restaurant.name}}</strong></h3>
               {% if restaurant.is_promot %}
                    <p class="card-text alert-success" style="text-align: center;"> PROMOTED RESTAURANT </p>
               {% endif %}
                <ul class="card-text list-group list-group-flush">
                    <li class="list-group-item"> <b> Menu Description:</b> {{restaurant.menu_description}} </li>
                    <li class="list-group-item"> <b>Price AVG:</b> {{restaurant.price_average}} €</li>
                    <li class="list-group-item"> <b>Rate:</b> {{restaurant.rate}}/5 </li>
                    <li class="list-group-item"> <b>Category:</b> {{restaurant.get_human_category}} </li>
                    <li class="list-group-item"> <b>City:</b> {{restaurant.city}} </li>
                    <li class="list-group-item"> <b>Address:</b> {{restaurant.address}} </li>
                    <li class="list-group-item"> <b>Country:</b> {{restaurant.country}} </li>
                </ul>
                <br>
                <form action="{% url 'reservation'%}" method="get">
                    <button class="btn btn-primary btn-lg btn-block" type="submit" name="reservation" value={{restaurant.restaurant_number}}>Make a Reservation</button>
                </form>
            </div>
        </div>
    </div>
</div>

<br><br>

<form method="POST" action="{% url 'review' restaurant.restaurant_number %}">
    <div class="form-group">
        {% csrf_token %}
        <label for="id_comment"> <h4>Make a Review:</h4> </label>
        <textarea name="comment" class="form-control" rows="3" placeholder="Comment here..." required id="id_comment"></textarea>
        <div class="form-group">
            <label for="id_ratios">Ratio:</label>
            <select class="form-control" name="ratio" required id="id_ratios">

                <option value="" selected>---------</option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>

            </select>
        </div>
        <br>
        <button class="btn btn-primary btn-block" type="submit">Review</button>
    </div>
</form>

<div style="width: 100%">
    <h3>Reviews:</h3>

    {% for rev in restaurant.comments.all %}
        <div class="media border p-3">
            <img src="https://s3.eu-west-3.amazonaws.com/sd2019-a4/images/user_default_image.jpg" alt="user static pic"  class="mr-3 mt-3 rounded-circle" style="width: 60px;">
            <div class="media-body">
                <h4><strong>{{rev.user.username}}</strong></h4>
                <p>{{rev.comment}}<br><br><strong>Rate: {{rev.ratio}} / 5</strong></p>
            </div>
        </div>
    {% endfor %}

</div>

{% endblock %}

templates/forkilla/home.html
{% extends 'forkilla/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}


<div class="jumbotron" style=" margin-top: 3rem; width: 100%;">
    <div style="align-items: center; padding: 2em 0 2em 0; text-align: center;">
        <h1><strong>Welcome to Forkilla</strong></h1>
        <h3>Where you can find many restaurants</h3>
        <a class="btn btn-primary btn-lg" href="{% url 'restaurants' %}"> Check the restaurants </a>
    </div>
</div>

{% if restaurants %}

    <h1 style="text-align: center;">Promoted Restaurants</h1>

    <hr>
    <div class="row" style="margin-left: -3.35rem; margin-right: 1rem;">
        <ul class="card-deck" >
            {% for restaurant in restaurants %}
                {% if restaurant.is_promot %}
                    <div class="col-3" style="width: 24vw;">
                        <div class="card" id="card-home">
                            <a href="{% url 'details' restaurant.restaurant_number %}">
                                <div class="featured-image" style="background-image:url('{{restaurant.featured_photo}}')" alt="{{restaurant.name}}"></div>
                            </a>
                            <div class="card-body">
                                <h5 class="card-title"><strong>{{restaurant.name}}</strong></h5>
                                <p class="card-text">{{restaurant.menu_description}}</p>
                            </div>
                        </div>
                        <br>
                    </div>
                {% endif %}
            {% endfor%}
        </ul>
    </div>
    <hr>

{% endif %}


{% endblock %}

templates/forkilla/reservation.html
{% extends 'forkilla/base.html' %}
{% block title %}{{restaurant.name}} Reservation{% endblock %}
{% block content %}

<div class="jumbotron" style="margin-top: 1.5rem;">
    <h2><strong> Starting reservation for: {{restaurant.name}} </strong></h2>

    <form method="POST" >
        {% csrf_token %}

        <div class="form-group">
            <label for="id_day">Day:</label>
            <input class="form-control" type="text" name="day" value="2019-05-22" required id="id_day" />
            <input class="form-control" type="hidden" name="initial-day" value="2019-05-22 20:31:11" id="initial-id_day" />
        </div>

        <div class="form-group">
            <label for="id_time_slot">Time slot:</label>
            <select class="form-control" name="time_slot" required id="id_time_slot">

                <option value="" selected>---------</option>
                <option value="morning_first">12h00</option>
                <option value="morning_second">13h00</option>
                <option value="morning_third">14h00</option>
                <option value="morning_fourth">15h00</option>
                <option value="evening_first">20h00</option>
                <option value="evening_second">21h00</option>
                <option value="evening_third">22h00</option>

            </select>
        </div>
        <div class="form-group">
            <label for="id_num_people">Num people:</label>
            <input  class="form-control" type="number" name="num_people" value="1" min="0" required id="id_num_people" />
        </div>

        <button class="btn btn-primary btn-block" type="submit">Save</button>
    </form>
    <hr>
    <button class="btn btn-danger btn-block" href="{% url 'details' restaurant.restaurant_number %}" type="submit">Cancel</button>
</div>
{% endblock %}